name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build the Docker image
      id: build
      run: |
        TIMESTAMP=$(date +%s)
        IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/unblocker
        docker build . --file Dockerfile --tag $IMAGE_NAME:$TIMESTAMP
        docker tag $IMAGE_NAME:$TIMESTAMP $IMAGE_NAME:latest
        echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push the Docker images to GitHub Container Registry
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/unblocker:$TIMESTAMP
        docker push ghcr.io/${{ github.repository_owner }}/unblocker:latest
