name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8 # specify the version of pnpm you need

    - name: Install dependencies
      run: |
        echo "Installing dependencies..."
        pnpm install 2>&1 | tee install.log
      continue-on-error: true

    - name: Test start application
      run: |
        echo "Starting application..."
        pnpm start > start.log 2>&1 &
        # Ensure the application starts correctly
        sleep 10
      continue-on-error: true

    - name: Print logs
      run: |
        echo "Installation logs:"
        cat install.log
        echo "Application start logs:"
        cat start.log
        # Optionally, you could use exit status checks here if needed
        if grep -q "error" start.log; then
          echo "Errors detected during application start."
          exit 1
        fi

    - name: Exit
      run: exit 0
